mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:8XxKfy5XUW9Ya9juBRyRU2N7kVNolTZ}
  schema: codeflix
  url: ${DATABASE_MYSQL_URL:localhost:3306}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none